### ISSUE TITLE
Keyboard interrupts

### ISSUE THREAD

**Issue by nicolewhite** [nicolewhite/cycli#1]

**Comment by jexp** [comment]
at least when on an empty line

**Comment by nicolewhite** [comment]
Also CTRL-D should too, according to Julian

**Comment by nicolewhite** [comment]
I think I'm going to mirror the Python REPL for CTRL+D and CTRL+C. CTRL+D exits the CLI if the current line is empty and CTRL+C clears your input but does not exit the CLI.
