### ISSUE TITLE
Insert matching parentheses, brackets, braces, and quotes

### ISSUE THREAD

**Issue by nicolewhite** [nicolewhite/cycli#17]
When you type any of the following opening characters, a closing version of the character should be inserted to the right of your cursor.

* `{` --> `}`
* `(` --> `)`
* `[` --> `]`
*  `"` --> `"`
* `'` --> `'`

**Comment by victoriastuart** [comment]
Nice feature / addition, but is there a shortcut (other than reaching over for the right-arrow key) to move out of the parentheses?  Thanks!  :-)
