### ISSUE TITLE
Cycli should support query parameters

### ISSUE THREAD

**Issue by igorclark** [nicolewhite/cycli#33]
Cycli currently can't execute Cypher queries using query parameters. It passes back compilation errors from the Cypher engine when parameters are referenced in a query, but it doesn't provide a way to define or examine their values, e.g. by using `export` or `env` as in the `neo4j-shell` client.

![image](https://cloud.githubusercontent.com/assets/164714/11368158/19cc2f36-9286-11e5-8297-051fd122d0cf.png)

**Comment by nicolewhite** [comment]
Thanks for the suggestion, I definitely want to add this. I like the syntax you are using as well of 

```
export key=value
```

**Comment by nicolewhite** [comment]
This is what I have so far 

![](http://i.imgur.com/hlS3J5h.png)

**Comment by igorclark** [comment]
Wow, fast, that looks great! Can I maybe help with testing somehow, as this progresses?

Also is that setting the env as a collection? In `neo4j-shell` it seems to just use a standard `key=value` environment variable list, but I guess a collection could work equally well, and especially if we could use collection functions on it?

**Comment by nicolewhite** [comment]
I don't follow. That's just a Python dictionary that's being printed. I could change the output to show what you would see when you type `env` in a regular terminal:

```
key1=value1
key2=value2
```

etc.

**Comment by nicolewhite** [comment]
Also ya, I can make a branch of this and we can work on it together.

**Comment by nicolewhite** [comment]
Is this better?

![](http://i.imgur.com/m7VJ19C.png)

**Comment by igorclark** [comment]
Yes, that's cool, nice one!

Re the dictionary, yeah, I thought for a (daft) moment there that the `env` data was somehow in a Neo4J collection. (Been looking at Cypher queries all day). But of course any `env` is going to be local, so that makes sense. So I guess output format isn't critical, but it sure helps the brain-eye muscle-memory having it in the same layout as bash like that. Thanks!

I'd be v happy to check out a branch and try it out on some of my queries that have multiple parameters in them, if that'd help. My python (& python-env-setup stuff) aren't super-strong, but I can certainly get it running to help test. LMK what I can do if that'll be useful :-)

One other thing I noticed working in `neo4j-shell` today is that you can set string parameters without quotes - again, not a massive deal, but would be neat, if it's not already possible...

**Comment by nicolewhite** [comment]
I pushed the changes to a branch called [params](https://github.com/nicolewhite/cycli/tree/params). You should check it out and let me know if you want anything changed before I bring it into master.

**Comment by nicolewhite** [comment]
Closed with https://github.com/nicolewhite/cycli/commit/453343643ea0f29b198fe37e5310efd8b974ff57.
