### ISSUE TITLE
Can connect and autosuggest node labels, but can't fire query

### ISSUE THREAD

**Issue by danpaulsmith** [nicolewhite/cycli#46]
______     __  __     ______     __         __
/\  ___\   /\ \_\ \   /\  ___\   /\ \       /\ \
\ \ \____  \ \____ \  \ \ \____  \ \ \____  \ \ \
 \ \_____\  \/\_____\  \ \_____\  \ \_____\  \ \_\
  \/_____/   \/_____/   \/_____/   \/_____/   \/_/

Using Bolt.
Version: 0.7.5
Bug reports: https://github.com/nicolewhite/cycli/issues

> MATCH (d:Species) RETURN d LIMIT 1;
Unable to connect to aws-neo4j on port 7687 - is the server running?

**Comment by nicolewhite** [comment]
Will you do me a favor and tell me if you can connect and run queries through py2neo?

**Comment by nicolewhite** [comment]
Hello, this was fixed in https://github.com/nicolewhite/cycli/commit/f9f0bcde2350361040fb58e061138b7666a7fb60
