### ISSUE TITLE
Semicolon in quoted property seems to be incorrectly interpreted as end of cypher statement

### ISSUE THREAD

**Issue by eyz** [nicolewhite/cycli#50]
When creating a node with a semicolon in the property value, the following error was produced. Perhaps the semicolon parsing isn't always being skipped inside quotes?

Please note that the troublesome code is rendered as a left arrow in this Github issue, as that is the HTML entity where the problematic semicolon parsing occurs. View source below to see the semicolon in context, or the attached screenshot of the code here -

![screenshot_20161208-231228-02](https://cloud.githubusercontent.com/assets/4591181/21039682/dd1094b8-bd9c-11e6-9700-2226903ead76.jpeg)

--------

MATCH (mno:ghi)
  where mno.id = "mno"
CREATE (def:ghi{id:"jkl",stu:"xyz &lArr;
Unexpected end of input: expected '\', ANY or '"' (line 4, column 131 (offset: 287))
"CREATE (def:ghi{id:"jkl",stu:"xyz &lArr;"
                                                                                                                                   ^

> abc",pqr:"xyz &lArr;
Invalid input '1': expected <init> (line 1, column 1 (offset: 0))
"abc",pqr:"xyz &lArr;"
 ^

I tried to redact the actual cypher, and hopefully that doesn't obfuscate it too much. I can add another case where this also happened in a where clause as well if that helps.

**Comment by nicolewhite** [comment]
Can you paste the exact query? You have a semicolon after xyz?

**Comment by eyz** [comment]
I had to obfuscate it. I don't have the query any longer. I suppose you can just close this if it doesn't help.

**Comment by eyz** [comment]
As I recall, when I removed the semicolon from the property value the cypher ran without errors in cycli

**Comment by eyz** [comment]
Nicole, please see the updated error. If that doesn't help identify the parser issue then I can try to isolate an example for you. This was only the output error I posted so far.

**Comment by nicolewhite** [comment]
Are you executing these queries from a file? Using `cycli --filename queries.txt` or something?

**Comment by nicodemus** [comment]
My guess is that is the case. From main.py:
> 
        if self.filename:
            queries = self.filename.read()
            queries = queries.split(";")[:-1]

> 
As it doesn't pay any attention to context (eg, quoted string), it looks like a semi-colon anywhere other than the end of a statement will break things.

**Comment by nicolewhite** [comment]
That's why I asked if he was using the `--filename` param. That code is only executed if you're saving queries/output to a file. That should be fixed regardless, but I'm trying to figure out if it's another bug.

**Comment by eyz** [comment]
Sorry for not responding yet. I am checking our scripts right now and will reply in a moment.

**Comment by nicolewhite** [comment]
Okay cool. I will fix this soon.
