### ISSUE TITLE
Setting a custom timeout

### ISSUE THREAD

**Issue by halflings** [nicolewhite/cycli#9]
Some queries take longer to be executed than py2neo's default timeout. cycli should provide a way to set this timeout. (py2neo.packages.httpstream.http.socket_timeout)

**Comment by nicolewhite** [comment]
I'm not able to force a timeout exception with `http.socket_timeout`.

```
>>> from py2neo import Graph
>>> from py2neo.packages.httpstream import http
>>> http.socket_timeout = 1
>>> graph = Graph()
>>> graph.cypher.execute("match p = ()-[*]-() return p")
```

Can you show me code where you've gotten a timeout exception?

**Comment by nicolewhite** [comment]
Nvm, I was able to figure it out.

**Comment by halflings** [comment]
Great! Thanks @nicolewhite.
